name: Build Nano11 ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Download Windows 11 ISO
      shell: pwsh
      run: |
        $isoUrl = 'https://software.download.prss.microsoft.com/dbazure/Win11_24H2_English_x64.iso?t=7beb5d6c-6cad-4234-9e87-804980ebc436&P1=1757908258&P2=601&P3=2&P4=HT3zAv8XdgVbY8svsu9ZbBRzkpJdRD%2bxgTbnUbee08giQjUIbnGeEmRS7cpZlgMQgE%2fVslixdv7a40nBdWOADuri%2bHDZOvjNfVvAMZ9KIlkSUv6%2bdv8%2bJVBAl1AIJj5Xdsd7tXRBMWu9%2f6iAebmd15UzuHWGbOgBy7TUqJz3wd5T8bEk3XgiWVag8NVXy%2fJ97dYRY3L7ZAkQMSJw6bTmksQcWqZMglF9bnYRpANlR06CquKDwwxgA9%2fWdj%2bRFQBsa8c%2f8ByRtboof0eJrQSYI64WHGm82KauJ9QPFclEv15GWhoNcn6RuGe9T92bTnbC87QQ8k8MPufJT2hczY4yjA%3d%3d'
        Invoke-WebRequest -Uri $isoUrl -OutFile 'C:\actions\work\windows11.iso'

    - name: Clone nano11
      shell: pwsh
      run: |
        git clone https://github.com/ntdevlabs/nano11.git

    - name: Run nano11 script
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        $mount = Mount-DiskImage -ImagePath 'C:\actions\work\windows11.iso' -PassThru
        Start-Sleep -Seconds 5
        $driveLetter = ($mount | Get-Volume).DriveLetter + ":"
        .\nano11\nano11builder.ps1 -SourceIsoDrive $driveLetter

    - name: Find built ISO
      id: findiso
      shell: pwsh
      run: |
        $iso = Get-ChildItem -Path .\nano11\*.iso | Select-Object -First 1
        echo "ISO=$($iso.FullName)" >> $env:GITHUB_ENV

    - name: Upload built ISO
      uses: actions/upload-artifact@v4
      with:
        name: nano11-custom-iso
        path: ${{ env.ISO }}
        overwrite: true
